<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payslip - {{ $monthName }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #333;
            font-size: 13px;
            line-height: 1.5;
            margin: 30px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header img {
            max-width: 120px;
        }

        .section-title {
            background-color: #f2f2f2;
            padding: 6px;
            font-weight: bold;
            margin-top: 20px;
            border: 1px solid #ddd;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 6px;
        }

        th, td {
            padding: 6px;
            border: 1px solid #ccc;
            text-align: left;
        }

        .totals {
            font-weight: bold;
            background-color: #f9f9f9;
        }

        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
        }

        .signature {
            margin-top: 60px;
            text-align: right;
            padding-right: 40px;
        }

        .signature p {
            margin: 0;
            font-weight: bold;
        }
    </style>
</head>
<body>

    <div class="header">
        <img src="{{ public_path('assets/images/wizweaver-Logo.png') }}" style="width:300px;" alt="Company Logo">
        <h2>Pay Slip - {{ $monthName }}</h2>
    </div>

    <div class="section-title">Employee Information</div>
    <table>
        <tr>
            <td><strong>Name:</strong></td><td>{{ $employee->user->name }}</td>
        </tr>
        <tr>
            <td><strong>Designation:</strong></td><td>{{ $employee->designation ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td><strong>Joining Date:</strong></td><td>{{ \Carbon\Carbon::parse($employee->created_at)->format('d M Y') ?? 'N/A' }}</td>
        </tr>
    </table>

    <div class="section-title">Earnings</div>
    <table>
        <tr>
            <td>Basic Salary</td>
            <td>{{ number_format($employee->salary, 2) }}</td>
        </tr>
        <tr>
            <td>Commission</td>
            <td>{{ number_format($payroll->commission, 2) }}</td>
        </tr>
        <tr>
            <td>Total Earnings</td>
            <td><strong>{{ number_format($payroll->base_salary + $payroll->commission, 2) }}</strong></td>
        </tr>
    </table>

    <div class="section-title">Deductions</div>
    <table>
        <tr>
            <td>Absent Deduction</td>
            <td>{{ number_format($payroll->deduction, 2) }}</td>
        </tr>
        <tr>
            <td>Income Tax</td>
            <td>{{ number_format($payroll->total_tax, 2) }}</td>
        </tr>
        <tr>
            <td>Total Deductions</td>
            <td><strong>{{ number_format($payroll->deduction + $payroll->total_tax, 2) }}</strong></td>
        </tr>
    </table>

    <div class="section-title">Net Payable</div>
    <table>
        <tr class="totals">
            <td>Net Salary (PKR)</td>
            <td>{{ number_format($payroll->total_pay, 2) }}</td>
        </tr>
    </table>

    <div class="signature">
        <p>___________________________</p>
        <p>Authorized Signature</p>
        <p>Generated By: Admin</p>
        <p>Date: {{ \Carbon\Carbon::now()->format('d M Y') }}</p>
    </div>

</body>
</html>
